### ISSUE TITLE
Add redux-saga and redux-loop solutions

### ISSUE THREAD

**Issue by gaearon** [DerekCuevas/friend-list#1]
I don’t have enough time to contribute this but https://github.com/yelouafi/redux-saga and https://github.com/raisemarketplace/redux-loop might provide nice solutions here.

cc @yelouafi and @raisemarketplace, maybe you’d like to contribute or ask people on your projects to prepare a PR

**Comment by DerekCuevas** [comment]
Awesome, I have been looking for more solutions. These two projects seem very fitting.

**Comment by lukewestby** [comment]
Neat! I can submit a redux-loop example in the next week or so.

**Comment by DerekCuevas** [comment]
Cool! @lukewestby I would be very interested in this.

**Comment by lukewestby** [comment]
#4 got something together tonight

**Comment by yelouafi** [comment]
Seems interesting. Will try to submit something this weekend

**Comment by yelouafi** [comment]
done, see #5

**Comment by DerekCuevas** [comment]
Thanks @yelouafi! Great solution, I merged it in and updated the README spec to point to your example for the concurrent actions issue. 

Also thanks to @gaearon for suggesting redux-saga.
