### ISSUE TITLE
Revision of the spec, ideas for solutions

### ISSUE THREAD

**Issue by DerekCuevas** [DerekCuevas/friend-list#9]
I'd like to ask for additions to the problem statement or spec. For example, debouncing requests, logging, adding loading and error states, ect. Anything that would make the problem statement more challenging or complete.

Also, solution proposals would be welcome here as well. Originally this was intended as a problem to be solved with a combination of react and redux. However, I won't deny solutions that don't use react or redux, especially if the solutions are of high quality.

I'll leave this issue open for a bit, to gather ideas.

**Comment by TylorS** [comment]
I'm open to any of these additions. These are the types of things Cycle/Motorcycle are designed to handle; all pretty easy stuff. 

Debouncing requests - one line of code

``` js
.debounce(100) // in milliseconds
```

Logging - one line of code

``` js
.do(x => console.log(x)) // or some function to format the logging
```

Loading/error states are as simple as a combination of adding a few `.merge()`s and `.filter()` s.
Depending on what is actually expected the LOC would vary a bit but not much would be required.

**Comment by TylorS** [comment]
Another thought could be animated reordering of the list

**Comment by DerekCuevas** [comment]
Ok, awesome.

I'm going to go ahead and add debouncing, logging, and loading / error states to the spec as bonus features. Animating reordering of the list would be cool, however it seems to be an unrelated problem to the one outlined in the README. What would adding animation highlight? Would this be a good addition for the Cycle.js and Motorcycle.js solutions?

I was thinking caching could make an OK addition to the spec as well. Although this might not be very fitting, as we would probably want to keep responses as fresh as possible if this app was not just a demo. What is your opinion on this?

I'll go ahead and add some of these features to my solutions later this week (most are already implemented in the better-observable-solution, but I'll add loading and error states for completeness). If you want to add some of these features to the Motorcycle.js solution that would be great! 

Thanks for your feedback!

**Comment by TylorS** [comment]
> I'm going to go ahead and add debouncing, logging, and loading / error states to the spec as bonus features

I will look for some time to add those to my motorcycle solution.

> What would adding animation highlight?

That's a good question. I don't know, I pretty much just think it'd be cool lol. It's not really too big of a deal for Motorcycle to handle, but you're probably right it doesn't really highlight anything specific to the challenge.

> we would probably want to keep responses as fresh as possible if this app was not just a demo

I don't think caching would be the best addition, as I agree with your above statement.
